import streamlit as st
import requests
import datetime

BASE_URL = "http://localhost:8000"  # Backend endpoint

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history (FIX 1: Add this loop)
st.header("How can I help you in planning a trip?")
for message in st.session_state.messages:
    with st.chat_message(message["role"]):  # FIX 4: Use chat_message
        st.markdown(message["content"])

# Chat input form
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_area(
        "Your question:", 
        placeholder="e.g., Plan a trip to Goa for 5 days with ₹50000 budget",
        height=100
    )
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    
    # FIX 2: Add user message to history and display
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)
    
    try:
        with st.spinner("Planning your trip... 🤖"):
            payload = {"query": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload, timeout=60)
        
        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            
            # FIX 5: Remove hardcoded name or use dynamic
            markdown_content = f"""# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}

---

{answer}

---

*This travel plan was generated by AI. Please verify all information before your trip.*
"""
            st.markdown(markdown_content)
            
            # FIX 3: Add assistant response to history
            st.session_state.messages.append({"role": "assistant", "content": markdown_content})
            
        else:
            error_msg = f"Bot failed to respond: {response.text}"
            st.error(error_msg)
            # Still add error as assistant response (optional)
            st.session_state.messages.append({"role": "assistant", "content": error_msg})
    
    except requests.exceptions.ConnectionError:
        error_msg = "Cannot connect to backend. Is FastAPI running on port 8000?"
        st.error(error_msg)
        st.session_state.messages.append({"role": "assistant", "content": error_msg})
    
    except requests.exceptions.Timeout:
        error_msg = "Request timed out. Please try again."
        st.error(error_msg)
        st.session_state.messages.append({"role": "assistant", "content": error_msg})
    
    except Exception as e:
        error_msg = f"Error: {str(e)}"
        st.error(error_msg)
        st.session_state.messages.append({"role": "assistant", "content": error_msg})
    
    # FIX 6: No raise - just rerun to show updated chat
    st.rerun()